### ISSUE TITLE
Improve Postprocessing multicore performace

### ISSUE THREAD

**Issue by troehling** [CFEL-CMI/pymepix#16]
The post-processing implementation is using the multiprocessing Pool. Currently only the clustering and centroid calculation is parallelised. An issue with this implementation is that the performance improvement is very small.

Comparison for one pyrrole raw dataset
Processing on a single core: 4:46
Processing on 6 cores (multiprocessing Pool): 3:35

The expected improvement should be significantly higher. I assume the issue is that the context of the pool is switched too often. Therefore the benefit is not that big. 

Possible solutions: 
- Implement multiprocessing for individual files: This should be fairly easy to implement. One drawback is that it does only provide a benefit if enough files are processed simultaneously. For single files the performance will be the same as for single cores.
- Integrate better with the online processing pipeline where multiprocessing is already implemented using queues. Right now I can not tell how large the benefit will be in this case.

**Comment by BenMoon** [comment]
This should be solved with f61b9a18e7a56da22a88026345124f0aa66aaf43
