### ISSUE TITLE
setup.py not configured properly

### ISSUE THREAD

**Issue by gmogol** [CFEL-CMI/pymepix#28]
When trying to install the package on a fresh computer, pip or setup.py doen't do a good job of installing the entire package. When trying to import one gets the following stack:

![Screenshot_2021-10-12T16-51-35](https://user-images.githubusercontent.com/10942319/137027413-2dec772a-b41a-4979-a5e8-6f23c16cc50b.png)

I have somehow gotten to install the package on my computer, when I was initially getting the same errors. Checking with a fresh computer we have realized that some files are missing. For example, centroiding.py and packetproccessor.py in processing folder were missing. Similarly in the package file itself post_processing.py was missing.

I realize that this has to do with your develop branch, which is the one that is currently not working and the master branch, which does work.

**Comment by troehling** [comment]
There were actually many changes in the development branch recently and its is still not everything working right now. I will take a look into this.

**Comment by troehling** [comment]
@gmogol I hope the installation is possible now even on the develop branch. I would recommend you to try this one again now as there should be many improvements included over the past 2 years that have not made it to the master branch yet (will probably merge in the upcoming weeks). If you have still any issues on the develop branch feel free to reopen or create a new issue.
